language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip list
  - pip install --upgrade pip
  - pip list
  - pip install --upgrade setuptools>=12.0
  - pip list
  - cd src; python setup.py develop
  - pip list
# command to run tests
script: make test
sudo: required
