# Control file for Travis CI (http://travis-ci.org)
# Must be located in the root directory of the Git repository.

sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

# commands to install dependencies
install:
  - python -c "import platform; print('Demonstration of incorrect distro returned by platform.linux_distribution():'); print(repr(platform.linux_distribution()))"
  - python -c "import pip, os; print('Site-packages directory of system Python:'); print(os.path.dirname(os.path.dirname(pip.__file__)))"
  - pip list
  - pip install --upgrade pip
  - python travis_remove_pbr.py
  - make clean
  - pip list
  - make develop
  - pip list
  - make check
  - make builddoc

# commands to run tests
script:
  - make test
